services:
  crestone-doc:
    container_name: crestone-doc
    image: cloudseidoranalytics/crestone-doc:latest
    restart: unless-stopped
    networks:
      - portal-mgmt

networks:
  portal-mgmt:
    external: true
